Github: use Rust v1.46.0 to build project
The project depends on the crate `clap', which needs a recent version
of the Rust compiler.  Otherwise, the following error is emitted:

   error[E0658]: `if` is not allowed in a `const fn`